[package]
name = "galacksi-orbit"
version = "0.1.0"
edition = "2021"
description = "Multiplayer space shooter based in the Galacksi universe"
authors = ["Asmov LLC <development.pub@asmov.software>"]
repository = "https://github.com/asmov/galacks-orbit"
license = "AGPL-3.0-or-later"
keywords = ["galacksi", "orbit", "multiplayer", "space", "shooter"]
categories = ["games"]

[dependencies]
ansi_term = "0.12.1"
bevy = { version="0.15", default-features = false, features = [
  #"android-game-activity",
  #"android-game-activity",
  #"android_shared_stdcxx",
  "animation",
  "bevy_asset",
  "bevy_audio",
  "bevy_color",
  "bevy_core_pipeline",
  "bevy_gilrs",
  "bevy_gizmos",
  #"bevy_gltf", FAILS w/bevy_tiling_background
  "bevy_mesh_picking_backend",
  #"bevy_pbr", FAILS w/bevy_tiling_background
  "bevy_picking",
  "bevy_render",
  "bevy_scene",
  "bevy_sprite",
  "bevy_sprite_picking_backend",
  "bevy_state",
  "bevy_text",
  "bevy_ui",
  "bevy_ui_picking_backend",
  "bevy_window",
  "bevy_winit",
  "custom_cursor",
  "default_font",
  "hdr",
  "multi_threaded",
  "png",
  "smaa_luts",
  "sysinfo_plugin",
  "tonemapping_luts",
  "vorbis",
  "webgl2",
  "x11",
  "wayland"
]}
bevy-steamworks = { optional = true, version = "0", features = ["serde"] }
#bevy_console = "0.13.1"
bevy_console = {path = "../../../../bevy-console" }
bevy_egui = "0.31" # bump with bevy_console
bevy_tiling_background = "0.12.0"
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"
strum = { version = "0", features = ["derive"] }

[features]
default = ["cli"]
#default = []
#default = ["cli", "steam"]
cli = []
steam = ["bevy-steamworks"]
